# Generated by Django 6.0.3 on 2026-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_email', models.EmailField(max_length=254)),
                ('destination_email', models.EmailField(max_length=254)),
                ('folder_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Running', max_length=20)),
                ('log_output', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
